Para efectos del ejercicio, se utilizó la misma base de datos exportada en formatos CSV y Excel, con el fin de simular la recepción de información desde distintas fuentes y verificar el correcto uso de las funciones read_csv() y read_excel() de Pandas
1. Carga de datos desde distintos archivos:
○ Importa un archivo CSV en un DataFrame de Pandas.
○ Carga un archivo Excel en otro DataFrame.
○ Extrae información de una tabla web utilizando read_html().

In [7]:
import pandas as pd

df_excel = pd.read_excel("Ventas_data_inventada.xlsx")
df_csv = pd.read_csv("Ventas_data_inventada.csv", encoding="latin1")
df_excel

    Nombre         Rut    Ventas
0   Camila  18456321-7  22290.90
1     Juan  20123456-9  26758.83
2    María  19874563-4  23354.66
3    Pedro  22457896-1  12817.38
4    María  19874563-4  27783.13
..     ...         ...       ...
94   Pablo  21896325-8  20139.29
95   Pablo  21896325-8  13075.19
96     Ana  17548963-2   5878.93
97   Pedro  22457896-1  11307.92
98   Carla  18965478-6  19771.34

[99 rows x 3 columns]

In [5]:
df_csv

              Nombre;Rut;Ventas
0   Camila;18456321-7; $22.291
1     Juan;20123456-9; $26.759
2    María;19874563-4; $23.355
3    Pedro;22457896-1; $12.817
4    María;19874563-4; $27.783
..                          ...
94   Pablo;21896325-8; $20.139
95   Pablo;21896325-8; $13.075
96      Ana;17548963-2; $5.879
97   Pedro;22457896-1; $11.308
98   Carla;18965478-6; $19.771

[99 rows x 1 columns]

In [ ]:
#La data de la web corresponde:población por país y año


url = "https://raw.githubusercontent.com/datasets/population/master/data/population.csv"

df_web = pd.read_csv(url)
df_web.head()

  Country Name Country Code  Year    Value
0        Aruba          ABW  1960  54922.0
1        Aruba          ABW  1961  55578.0
2        Aruba          ABW  1962  56320.0
3        Aruba          ABW  1963  57002.0
4        Aruba          ABW  1964  57619.0

2. Limpieza y estructuración de datos:
○ Identifica valores nulos y decide si deben ser imputados o eliminados.
○ Elimina filas duplicadas si es necesario.
○ Verifica y ajusta los tipos de datos en columnas numéricas y categóricas.

In [12]:
#detectar valores nulos
df_excel.isnull().sum()

Nombre    0
Rut       0
Ventas    4
dtype: int64

In [16]:
df_excel = df_excel.dropna(subset=["Ventas"])
df_excel.isnull().sum()

Nombre    0
Rut       0
Ventas    0
dtype: int64

In [14]:
#   Ver duplicados exactos
df_excel.duplicated().sum()

0

In [ ]:
#Revisar tipos de datos actuales
df_excel.dtypes
#se vizualiza que los datos estan correctamente asignados

Nombre     object
Rut        object
Ventas    float64
dtype: object

3. Transformación y optimización de datos:
○ Selecciona las columnas más relevantes para el análisis.
○ Renombra columnas para mejorar la legibilidad.
○ Ordena los datos en función de una columna clave.

In [17]:
df_excel = df_excel[['Nombre', 'Ventas']]
df_excel

    Nombre    Ventas
0   Camila  22290.90
1     Juan  26758.83
2    María  23354.66
3    Pedro  12817.38
4    María  27783.13
..     ...       ...
94   Pablo  20139.29
95   Pablo  13075.19
96     Ana   5878.93
97   Pedro  11307.92
98   Carla  19771.34

[95 rows x 2 columns]

In [19]:
#ordenar datos en base una columna
df_excel = df_excel.sort_values(by='Ventas', ascending=False)
df_excel

    Nombre      Ventas
90  Camila  6626370.57
16   Pablo  5518033.38
6   Camila  2220001.00
57   María    29926.35
60  Camila    29737.77
..     ...         ...
75   Pedro     3541.76
73   Pedro     3330.79
80   Pablo     3275.78
61   Sofía     1666.82
19   Carla     1646.95

[95 rows x 2 columns]

In [ ]:
"""
Se puede observar qeu quedaron unos datos adicionales muy altos en Ventas. 
Lo que sugiere que faltó eliminar outliers
"""

4. Exportación de datos:
○ Guarda el DataFrame limpio en un archivo CSV sin incluir el índice.
○ Exporta los datos procesados a Excel para su visualización.

In [20]:
#Guardar el DataFrame limpio en CSV (sin índice)
df_excel.to_csv('datos_limpios.csv', index=False)

In [21]:
#Exportar los datos procesados a Excel
df_excel.to_excel('datos_limpios.xlsx', index=False)

In [ ]:
#Los archivos se guarda en la carpeta donde se trabaja(directorio de trabajo)

#4. Conclusiones sobre la importancia de un proceso estructurado de obtención de datos.

Un proceso estructurado de obtención de datos es fundamental para asegurar la calidad, confiabilidad y utilidad de la información analizada. La correcta recopilación, limpieza, transformación y validación de los datos permite reducir errores, evitar inconsistencias y facilitar el análisis posterior. Además, trabajar con datos bien organizados mejora la toma de decisiones, optimiza el tiempo de trabajo y garantiza resultados más precisos y reproducibles. En este contexto, contar con un flujo ordenado desde la obtención hasta la exportación de los datos es clave para cualquier proyecto de análisis de datos.