# Manejo de outliers

In [1]:
import pandas as pd
import numpy as np

In [55]:
df=pd.DataFrame({'oldName': [1, 2, 3], 'anotherOldName': ['a', 'b', 'c']}) 

#renombrar columnas de un DataFrame
print(df)
print("------------------   ------------------")
df.rename(columns={'oldName': 'newName', 'anotherOldName': 'anotherNewName'}, inplace=True)
print(df)
print("------------------   ------------------")
  
#cambiar valores de una columna
df["anotherNewName"] = df["anotherNewName"].replace({'a': 'x','b': 'y','c': 'z'}) 
print(df)
print("------------------   ------------------")
#cambiar valores de una columna
df["anotherNewName"] = df["anotherNewName"].replace('x', 'nuevoValor') 
print(df)
print("------------------   ------------------")
#cambiar valores de una columna
df["anotherNewName"].replace('nuevoValor', 'asdfghjkl', inplace=True) 
print(df)

   oldName anotherOldName
0        1              a
1        2              b
2        3              c
------------------   ------------------
   newName anotherNewName
0        1              a
1        2              b
2        3              c
------------------   ------------------
   newName anotherNewName
0        1              x
1        2              y
2        3              z
------------------   ------------------
   newName anotherNewName
0        1     nuevoValor
1        2              y
2        3              z
------------------   ------------------
   newName anotherNewName
0        1      asdfghjkl
1        2              y
2        3              z

C:\Users\l\AppData\Local\Temp\ipykernel_26920\2707741041.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["anotherNewName"].replace('nuevoValor', 'asdfghjkl', inplace=True)

In [56]:
df.isnull().sum() #nulos por columna  
(df.isnull().sum() / len(df)) * 100 #porcentaje de nulos por columna  
df.isnull().sum().sum() #nulos totales
df.dropna(thresh=2) #elimina filas: thresh=2 → mínimo 2 datos válidos.Menos de eso → se elimina

   newName anotherNewName
0        1      asdfghjkl
1        2              y
2        3              z

In [101]:
df = pd.DataFrame({
    "Nombre": [
        "Ana", "Luis", "María", "Pedro", "Sofía",
        "Jorge", "Camila", "Diego", "Valentina", "Carlos",
        "Fernanda", "Andrés", "Paula", "Ricardo", "Daniela",
        "Tomás", "Claudia", "Felipe", "Antonia", "Miguel"
    ],
    "Area trabajo": [
        "IT", "Ventas", "IT", "Marketing", "Ventas",
        "IT", "RRHH", "Ventas", "Marketing", "IT",
        "RRHH", "Ventas", "IT", "Marketing", "Ventas",
        "IT", "RRHH", "Marketing", "Ventas", "IT"
    ],
    "Salario": [
        1200, 6000, 1300, 1100, 1050,
        None, 1150, 980, None, 1250,
        1400, None, 1350, 1120, 1080,
        None, 1500, 1180, 1020, None
    ]
})
print(df)

       Nombre Area trabajo  Salario
0         Ana           IT   1200.0
1        Luis       Ventas   6000.0
2       María           IT   1300.0
3       Pedro    Marketing   1100.0
4       Sofía       Ventas   1050.0
5       Jorge           IT      NaN
6      Camila         RRHH   1150.0
7       Diego       Ventas    980.0
8   Valentina    Marketing      NaN
9      Carlos           IT   1250.0
10   Fernanda         RRHH   1400.0
11     Andrés       Ventas      NaN
12      Paula           IT   1350.0
13    Ricardo    Marketing   1120.0
14    Daniela       Ventas   1080.0
15      Tomás           IT      NaN
16    Claudia         RRHH   1500.0
17     Felipe    Marketing   1180.0
18    Antonia       Ventas   1020.0
19     Miguel           IT      NaN

In [102]:
df.iloc[5,0]

'Jorge'

In [103]:
df.loc[5, 'Area trabajo'] = np.nan
print(df.head(10))
print("------------------   ------------------")
df.iloc[8,1] = np.nan
df.iloc[8,0] = np.nan
print(df.head(10))

      Nombre Area trabajo  Salario
0        Ana           IT   1200.0
1       Luis       Ventas   6000.0
2      María           IT   1300.0
3      Pedro    Marketing   1100.0
4      Sofía       Ventas   1050.0
5      Jorge          NaN      NaN
6     Camila         RRHH   1150.0
7      Diego       Ventas    980.0
8  Valentina    Marketing      NaN
9     Carlos           IT   1250.0
------------------   ------------------
   Nombre Area trabajo  Salario
0     Ana           IT   1200.0
1    Luis       Ventas   6000.0
2   María           IT   1300.0
3   Pedro    Marketing   1100.0
4   Sofía       Ventas   1050.0
5   Jorge          NaN      NaN
6  Camila         RRHH   1150.0
7   Diego       Ventas    980.0
8     NaN          NaN      NaN
9  Carlos           IT   1250.0

In [105]:
df.dropna(thresh=1,inplace=True) ##elimina filas: thresh=1 → mínimo 1 datos válidos.menos de eso → se elimina
#aqui se fue el dato 8 porque tenia solo un valor en la fila.
#df.dropna(thresh=2) # thresh=2 → eliminaria dos filas: la 5 y la 8 
print(df)

      Nombre Area trabajo  Salario
0        Ana           IT   1200.0
1       Luis       Ventas   6000.0
2      María           IT   1300.0
3      Pedro    Marketing   1100.0
4      Sofía       Ventas   1050.0
5      Jorge          NaN      NaN
6     Camila         RRHH   1150.0
7      Diego       Ventas    980.0
9     Carlos           IT   1250.0
10  Fernanda         RRHH   1400.0
11    Andrés       Ventas      NaN
12     Paula           IT   1350.0
13   Ricardo    Marketing   1120.0
14   Daniela       Ventas   1080.0
15     Tomás           IT      NaN
16   Claudia         RRHH   1500.0
17    Felipe    Marketing   1180.0
18   Antonia       Ventas   1020.0
19    Miguel           IT      NaN

In [106]:
#df.dropna()#elimina todas las filas que tengan valores NaN
#df.dropna(axis=0)
df.dropna(axis=1) #elimina columnas con valores NaN

      Nombre
0        Ana
1       Luis
2      María
3      Pedro
4      Sofía
5      Jorge
6     Camila
7      Diego
9     Carlos
10  Fernanda
11    Andrés
12     Paula
13   Ricardo
14   Daniela
15     Tomás
16   Claudia
17    Felipe
18   Antonia
19    Miguel

In [108]:
df.groupby("Area trabajo")["Salario"].mean().sort_values(ascending=False)

Area trabajo
Ventas       2026.000000
RRHH         1350.000000
IT           1275.000000
Marketing    1133.333333
Name: Salario, dtype: float64

In [46]:
df["Salario"] = df["Salario"].fillna(
    df.groupby("Area trabajo")["Salario"].transform("mean")
)
df

       Nombre Area trabajo      Salario
0         Ana           IT  1200.000000
1        Luis       Ventas  6000.000000
2       María           IT  1300.000000
3       Pedro    Marketing  1100.000000
4       Sofía       Ventas  1050.000000
5       Jorge           IT  1275.000000
6      Camila         RRHH  1150.000000
7       Diego       Ventas   980.000000
8   Valentina    Marketing  1133.333333
9      Carlos           IT  1250.000000
10   Fernanda         RRHH  1400.000000
11     Andrés       Ventas  2026.000000
12      Paula           IT  1350.000000
13    Ricardo    Marketing  1120.000000
14    Daniela       Ventas  1080.000000
15      Tomás           IT  1275.000000
16    Claudia         RRHH  1500.000000
17     Felipe    Marketing  1180.000000
18    Antonia       Ventas  1020.000000
19     Miguel           IT  1275.000000

In [47]:
print(df)

       Nombre Area trabajo      Salario
0         Ana           IT  1200.000000
1        Luis       Ventas  6000.000000
2       María           IT  1300.000000
3       Pedro    Marketing  1100.000000
4       Sofía       Ventas  1050.000000
5       Jorge           IT  1275.000000
6      Camila         RRHH  1150.000000
7       Diego       Ventas   980.000000
8   Valentina    Marketing  1133.333333
9      Carlos           IT  1250.000000
10   Fernanda         RRHH  1400.000000
11     Andrés       Ventas  2026.000000
12      Paula           IT  1350.000000
13    Ricardo    Marketing  1120.000000
14    Daniela       Ventas  1080.000000
15      Tomás           IT  1275.000000
16    Claudia         RRHH  1500.000000
17     Felipe    Marketing  1180.000000
18    Antonia       Ventas  1020.000000
19     Miguel           IT  1275.000000

In [109]:
#cuartiles
Q1 = df["Salario"].quantile(0.25)
Q2 = df["Salario"].quantile(0.50) #mediana
Q3 = df["Salario"].quantile(0.75)
print(f"Q1: {Q1}, Q2: {Q2}, Q3: {Q3}")
IQR = Q3 - Q1
print(f"IQR: {IQR}")
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(f"Limite inferior: {lower_bound}, Limite superior: {upper_bound}")
print("cualquier valor fuera de estos límites es un outlier")
print(df[(df["Salario"] < lower_bound) | (df["Salario"] > upper_bound)])
print("-------------------   ------------------")
print(df[(df["Salario"] >= lower_bound) & (df["Salario"] <= upper_bound)])

Q1: 1090.0, Q2: 1180.0, Q3: 1325.0
IQR: 235.0
Limite inferior: 737.5, Limite superior: 1677.5
cualquier valor fuera de estos límites es un outlier
  Nombre Area trabajo  Salario
1   Luis       Ventas   6000.0
-------------------   ------------------
      Nombre Area trabajo  Salario
0        Ana           IT   1200.0
2      María           IT   1300.0
3      Pedro    Marketing   1100.0
4      Sofía       Ventas   1050.0
6     Camila         RRHH   1150.0
7      Diego       Ventas    980.0
9     Carlos           IT   1250.0
10  Fernanda         RRHH   1400.0
12     Paula           IT   1350.0
13   Ricardo    Marketing   1120.0
14   Daniela       Ventas   1080.0
16   Claudia         RRHH   1500.0
17    Felipe    Marketing   1180.0
18   Antonia       Ventas   1020.0